name: First workflow

on: [push]

jobs:
  build:                            # nombre del job, build es totalmente arbitrário
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1   # action encapsulada, en https://github.com/actions/checkout@v1
      - name: Hello world
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"
